USE [master]
GO

/****** Object:  Database [NeemDB]    Script Date: 01-06-2020 18:37:30 ******/
CREATE DATABASE [NeemDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NeemDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\NeemDB.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NeemDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\NeemDB_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [NeemDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NeemDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NeemDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NeemDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NeemDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NeemDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NeemDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [NeemDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [NeemDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NeemDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NeemDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NeemDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NeemDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NeemDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NeemDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NeemDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NeemDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [NeemDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NeemDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NeemDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NeemDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NeemDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NeemDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [NeemDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NeemDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NeemDB] SET  MULTI_USER 
GO

ALTER DATABASE [NeemDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NeemDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NeemDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NeemDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NeemDB] SET  READ_WRITE 
GO


